.\" $Id: gextractwinicons.1 0.3 2013-10-27 19:56 muflone $
.\"
.\" Copyright (c) 2009-2014 Fabio Castelli

.TH GEXTRACTWINICONS "1" "October 27, 2013"

.SH NAME
.B gExtractWinIcons
\- Extract cursors and icons from MS Windows compatible resource files

.SH SYNOPSIS
.B gextractwinicons
\-h
.br
.B gextractwinicons
[options]

.SH DESCRIPTION
.PP
.B gExtractWinIcons
is a GTK+ utility to extract cursors, icons and png images from MS Windows
compatible resource files (.exe, .dll, .ocx, .cpl and many others).

.PP
To extract icons or cursors just to select a MS Windows compatible resource
file and the contained resources will be shown. Select a destination directory
where to save the selected resources, simply check the items to extract and
press the save button to save them in the specified path.

.SH "OPTIONS"
This program follow the usual GNU command line syntax, with long
options starting with two dashes (`\-').
A summary of options is included below.
.TP 
.B \-h, \-\-help
Show summary of options
.TP 
.B \-v, \-\-verbose
Be verbose (print additional useful status messages)
.TP 
.B \-q, \-\-quiet
Do not print any output to the stdout
.TP 
.B \-d, \-\-destination
Set destination folder for extracted resources
.TP 
.B \-f, \-\-filename
Set resources filename from which to extract the resources
.TP 
.B \-r, \-\-refresh
Automatically refresh the resources list if \-f (\-\-filename) was specified
.TP 
.B \-n, \-\-nofreeze
Do not freeze the treeview during the refresh (slower)

.SH REPORTING BUGS
Report bugs to https://github.com/muflone/gextractwinicons/issues

.SH AUTHORS
.B gExtractWinIcons
was written by Fabio Castelli (Muflone) <muflone@vbsimple.net>

.SH HOMEPAGE
Home page: http://www.muflone.com/gextractwinicons

Source code: https://github.com/muflone/gextractwinicons/

.SH COPYRIGHT
Copyright © 2009-2014 Fabio Castelli.
License GPLv2+: GNU GPL version 2 or later <http://www.gnu.org/licenses/gpl-2.0.html>.

This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
